---
version: "3"
services:

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    hostname: 'gitlab'
    environment:
    - TZ=America/Sao_Paulo
    ports:
      - '8000:80'
      - '8443:443'
      - '2222:22'
    networks:
      - gitlab-network
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'

  jenkins:
    image: jenkins/jenkins:lts
    hostname: 'jenkins'
    ports:
      - '8080:8080'
      - '50000:50000'
    networks:
      - gitlab-network
    volumes:
      - 'jenkins_home:/var/jenkins_home'

volumes:
  gitlab-data:
  gitlab-logs:
  gitlab-config:
  jenkins_home:

networks:
  gitlab-network:
    driver: bridge
