---
version: "3"
services:

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    hostname: 'gitlab'
    environment:
    - TZ=America/Sao_Paulo
    - GITLAB_HTTPS=false
    - GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8000'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        
    ports:
      - '8000:8000'
      - '8443:8443'
      - '2224:22'
    networks:
      - gitlab-network
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'

  jenkins:
    image: jenkins/jenkins:lts
    hostname: 'jenkins'
    ports:
      - '8080:8080'
      - '50000:50000'
    networks:
      - gitlab-network
    volumes:
      - 'jenkins_home:/var/jenkins_home'

  sonarqube:
    image: 'sonarqube:latest'
    hostname: 'sonarqube'
    ports:
      - '9000:9000'
    networks:
      - gitlab-network
    volumes:
      - 'sonarqube_conf:/opt/sonarqube/conf'
      - 'sonarqube_data:/opt/sonarqube/data'
      - 'sonarqube_logs:/opt/sonarqube/logs'
      - 'sonarqube_extensions:/opt/sonarqube/extensions'

volumes:
  gitlab-data:
  gitlab-logs:
  gitlab-config:
  jenkins_home:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

networks:
  gitlab-network:
    driver: bridge
